groups:
  - name: instance-health
    rules:
      - alert: BackendDown
        expr: up{job="backend"} == 0  '
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Backend ne r√©pond plus"
          description: "Le backend zou.local est down depuis plus d'une minute."

