apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# CORRECTION : liste tous les fichiers YAML individuellement
resources:
  - alertmanager-configmap.yaml
  - alertmanager-deployment.yaml
  - alert-rules-deployment.yaml
  
  - configmap-node-exporter.yaml
  - ingress-prometheus.yaml
  - postgres-exporter-deployment.yaml
  - prometheus-configmap.yaml
  - prometheus-deployment.yaml
