apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
 -configmap-node-exporter.yaml
 -ingress-prometheus.yaml
 -postgres-exporter-deployment.yaml
 -prometheus-configmap.yaml
 -prometheus-deployment.yaml
 -alertmanager-configmap.yaml
 -alertmanager-deplyement.yaml
 -alert-rules.yaml
 -alert-rules-deployment.yaml


